# Generated by Django 4.1.3 on 2023-01-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_detection', '0003_video_feed_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_feed',
            name='is_in_charge',
            field=models.BooleanField(default=False),
        ),
    ]
